@startuml
' Style definitions
skinparam componentStyle uml2
skinparam component {
    BackgroundColor #2C5773
    FontColor white
    BorderColor Black
}


package "Input" {
    [Depth Image] as depth_img
    [Raw Image] as raw_img
    [Robot localization] as localization
}

package "Shepherd" {
    ' Components
    [Object detection (YOLO)] as yolo
    [Object segmentation (FastSAM)] as fast_sam
    [Depth estimation (DAN, Optional)] as dan
    [Image-text similarity (CLIP)] as clip
    [World manipulator] as coord_transform
    [Image captioning (BLIP)] as blip
    
    ' Databases    
    database "DB" as db

    ' Data interfaces
    interface "image depth map" as depth_map_if
    interface "masks" as mask_if
    interface "cropped images" as cropped_images_if
}

package "Output" {
    interface "Object map" as object_map
}


' Connections
raw_img --> yolo
raw_img --> dan
dan --> depth_map_if
depth_img --> depth_map_if
yolo --> fast_sam : bounding boxes
fast_sam --> mask_if
raw_img -right-> cropped_images_if
mask_if --> cropped_images_if
cropped_images_if --> clip
cropped_images_if --> blip
blip --> db
clip --> db
localization --> coord_transform
depth_map_if --> coord_transform
mask_if --> coord_transform
coord_transform --> db : object 3d shape, position
db --> object_map

yolo -[hidden]r-> dan
@enduml